### ISSUE TITLE
Conflict numeric biblio-style

### ISSUE THREAD

**Issue by VitaliKStud** [bchwtz/fhswf#1]
https://github.com/bchwtz/fhswf/blob/cfd7dacc38cb209a1326a6f51c9fb73386845773/inst/rmarkdown/templates/fhswf-seminarpaper/resources/fhswf-seminarpaper.tex#L572

Hi,

there is a conflict if I would like to use:

EXAMPLE
###########################
bibliography: references.bib
biblio-style: numeric
###########################

Probably needed something like if "authoryear-comp" then keep this else delete this line.

$if(biblio-style == "authoryear-comp")$
\ExecuteBibliographyOptions{bibencoding=utf8,minnames=1,maxnames=3, maxbibnames=99,dashed=false,terseinits=true,giveninits=true,uniquename=false,uniquelist=false,doi=false, isbn=false,url=true,sortcites=false}
$endif$

Thx, best regards

**Comment by the-snork** [comment]
dashed is only defined in authortitle.bbx and authoryear.bbx (in biblatex) and these are used in a plenty of styles.

imho it would be easier to pass have the options configurable in r; the whole biblio-style handling might need some rework. here, it seems like a fixed style is loaded in any case: [https://github.com/bchwtz/fhswf/blob/88796279359e89a1716cc5ed74bc88062990ca68/inst/rmarkdown/templates/fhswf-seminarpaper/resources/fhswf-seminarpaper.tex#L588](url)
